package com.ist.leavemanagementsystem.model;

import jakarta.persistence.*; // Use jakarta persistence
import lombok.Data; // Add Lombok
import lombok.NoArgsConstructor; // Add Lombok

@Entity
@Table(name = "leave_types") // Add table name mapping
@Data // Add Lombok
@NoArgsConstructor // Add Lombok
public class LeaveType {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false, unique = true, length = 255) // Add constraints from schema
    private String name; // e.g., "Personal Time Off", "Sick Leave"

    @Column(nullable = false)
    private Integer defaultDays;

    // Getters and setters are generated by @Data
    // NoArgsConstructor is generated by @NoArgsConstructor
}