package com.ist.leavemanagementsystem.model;

import jakarta.persistence.*; // Ensure necessary JPA imports
import lombok.Data; // Using Lombok for boilerplate code
import lombok.NoArgsConstructor; // Add NoArgsConstructor for JPA

@Entity
@Table(name = "leave_balances") // Specify the table name
@Data // Using Lombok for getters, setters, toString, equals, hashCode
@NoArgsConstructor // Add a no-args constructor required by JPA
public class LeaveBalance {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Use IDENTITY for auto-incrementing IDs
    private Long id;

    @Column(name = "user_id", nullable = false)
    private Long userId;

    // Added based on FirstPick: Link to LeaveType
    @Column(name = "leave_type_id", nullable = false)
    private Long leaveTypeId;

    // Changed field name and type based on FirstPick
    @Column(nullable = false, columnDefinition = "SMALLINT default 0")
    private int entitlement = 0; // This is the number of days HR will give to the user

    // Changed field name and type based on FirstPick
    @Column(nullable = false, columnDefinition = "SMALLINT default 0")
    private int used = 0;

    // Added based on FirstPick
    @Column(nullable = false, columnDefinition = "SMALLINT default 0")
    private int remaining = 0;

    // Note: Getters, Setters, equals, hashCode, and toString are generated by
    // Lombok's @Data
    // Note: A no-args constructor is generated by Lombok's @NoArgsConstructor
}