package com.ist.leavemanagementsystem.model;

import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.CreationTimestamp; // For default timestamp

import java.time.OffsetDateTime; // Use OffsetDateTime for TIMESTAMP WITH TIME ZONE

@Entity
@Table(name = "notifications")
@Data
@NoArgsConstructor
public class Notification {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "recipient_id", nullable = false)
    private User recipient; // Renamed from recipient_id for clarity

    @Column(columnDefinition = "TEXT")
    private String message;

    @Column(length = 100)
    private String type; // e.g., LEAVE_SUBMITTED, APPROVED, REJECTED

    @Column(nullable = false, columnDefinition = "BOOLEAN default FALSE")
    private boolean read = false;

    @CreationTimestamp // Automatically set on creation
    @Column(nullable = false, updatable = false, columnDefinition = "TIMESTAMP WITH TIME ZONE")
    private OffsetDateTime timestamp;

    // Getters and setters are generated by @Data
    // NoArgsConstructor is generated by @NoArgsConstructor
}
